contents:
  README:
    file: README.md
  intertrain:
    crevasse_map:
      file: intertrain/crevasse_map.tif
    earthobservation_map:
      file: intertrain/earthobservation_map.tif
  train:
    X_data:
      file: train/X_data.npy
    Y_data:
      file: train/Y_data.npy
